name: dataclass
description: DataClass annotation for dataclass_generator. Used for generating base class with equals, hashCode, toString, copyWith methods.
version: 0.1.0+1
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>
homepage: https://github.com/jarekb123/dart_dataclass

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
