name: dataclass_generator
description: DataClass annotation for dataclass_generator. Used for generating base class with equals, hashCode, toString, copyWith methods.
version: 0.2.2
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>
homepage: https://github.com/jarekb123/dart_dataclass

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  dataclass: ^0.2.0
  # dataclass:
    # path: ../dataclass/
  build: ">=1.2.0 <1.3.0"
  source_gen: ">=0.9.0 <0.10.0"
  code_builder: ">=3.2.0 <3.3.0"
  dart_style: ">=1.3.0 <1.4.0"
  analyzer: ">=0.39.0 <0.40.0"

dev_dependencies:
  build_test:
  build_runner:
  test:
